# Site settings
title: BlueRobotics Product Documentation Site
email: info@bluerobotics.com
description: > # this means to ignore newlines until "baseurl:"
  The BlueRobotics documentation site has instructions, tutorials, and guides for
  using BlueRobotics' products. You can contribute through Github!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.bluerobotics.com" # the base hostname & protocol for your site
twitter_username: bluerobotics
github_username:  bluerobotics

# Build settings
markdown: kramdown